### PR TITLE
First commit!

### PR DESCRIPTION
**Pull request by sandramchung**
We want to do this in Jekyll

### CODE REVIEW

**Comment by sreynen** [comment]
Some questions:

1) Why?
2) How would we do authentication in Jekyll?
3) How would we do search in Jekyll?
4) How would non-developers add/edit content?

**Comment by jnettik** [comment]
From an IA perspective, at least in my limited experience with Jekyll, it's suited for blogs. However it doesn't scale outside that well, and we have several types of content we could be dealing with. Also, non-devs is a concern for me as well.

**Comment by robballou** [comment]
Out of the box, Jekyll's a blog so posts live in a folder and need to be date based which could be problematic (not all our content is date-based). And what @jnettik said ;)

**Comment by pixelwhip** [comment]
Things I like about Jekyll that are certainly not limited to Jekyll
1. Liquid Templates (I'd be up for Twig or nunjucks too)
2. Markdown + YAML

**Comment by sandramchung** [comment]
1) Jekyll is fast and easy and we don't already use it. 
2) We'd have to add an external application for auth. Could use OpenID.
3) https://github.com/christian-fei/Simple-Jekyll-Search
4) Prose provides an editing UI for github, which is a way for any github user to create content if we're hosting this site in github.

**Comment by sandramchung** [comment]
Let's backup and talk about functionality. Here's what we've got so far:
* search should work really well
* we should be able to search by content type/ category
* authoring and editing experience should be lightweight and fast. Markdown-based editing seems like the way to go
* need tagging system
* lots of content interlinking - maybe a More Like This functionality - to facilitate navigation
* subscription to specific tags/content types

**Comment by sandramchung** [comment]
Maybe we should talk about a requirements as a group before we race to develop.

**Comment by Josh-Miller** [comment]
From Team Red:

MVP Requirements

* Searchable
* Authentication
* Content storage
* Usability
* Relatable content
* Revisible content (git)

Content Editing
* Socket.io to allow multiple editors at once

* Use sqlite to relate flat files

**Comment by sandramchung** [comment]
https://www.atlassian.com/software/confluence 
Confluence integrates easily with JIRA, which already has a ton of our documentation.

**Comment by sreynen** [comment]
Confluence looks like it could handle most, maybe all of our stated MVP requirements, but I'm going to add a new requirement that I just sort of took as a given before: this should be open source, so we and others can gradually improve it over time.

**Comment by sandramchung** [comment]
Open source, flexible, functional documentation platform is a problem
that's already been solved many times over. Lots of our requirements point
to wikis, which address most or all of our tech requirements (and can
essentially duplicate what we have right now). The reason our documentation
has gotten annoying and needs an overhaul is because like any wiki, it
needs tons of active content management and editing to maintain its
usefulness. We're not going to solve the Wikipedia editors problem with any
kind of code, open source or not, in a dev meeting.

If the goal of this exercise is to create something that meets our
documentation needs that is also more widely useful and open-source, let's
aim to solve a contrib module-sized problem that we can solve in a dev
meeting-sized chunk of time. We can add to an existing open-source platform
that's already widely used, so our contribution is more likely to be used
and perpetuated by other people in addition to us. Pegacorn is a great
non-open source example; it's essentially a Harvest plug-in.

Adding git version control to the content itself is something developers,
and not mainstream users, would be interested in. Lots of wiki/content
management systems already do version control, though.

If we built something that would export existing content from a database
into a structured git repository of markdown files, it would be really
simply to move that content into a database-less environment like Jekyll
(which already git version-controls content). Then we can add the
non-techie interface to content version control, and maybe even apply or
build on an existing open-source git GUI.

I think lots of people might be excited about an easy way to migrate
structured content from uncomplicated Drupal or Wordpress sites into
database-free, static sites. Some of what we do here could be steps toward
building a Jekyll CMS, which I have talked about before and I still think
it would be huge. Another option is to try and marry git to a database, but
that does not sound fun or bite-size to me. I'd prefer to break the content
out of a database and into a space that's already easy to git control.

In addition, Joe, Ferris, James, Clayton and I talked about automatically
pulling README content from a repository into an external documentation
site. That could be really handy for us and bite-sized to build as well.

**Comment by sreynen** [comment]
The general goal here is to build a better documentation system. "Better" is still largely undefined, and I suspect defining goals will be the first accepted PR. Certainly any other PR is going to be met with questions about goals until those are defined.

Git for content interests me because it would allow distributed editing, which I expect would be better than what we have by encouraging more active use. I would personally add and edit documentation more if it were as simple as editing a local file, and suspect others would as well. (If only we had some way to survey users, we could know for sure.) Git as a command-line interface is developer-centric, but distributed editing is not, as Google Drive demonstrates. And prose.io demonstrates that the distributed editing features of Git can be used without the CLI.

Content maintenance seems like another big opportunity for improvement. That's not a major consideration for most web tools, and certainly wasn't a major consideration for our current documentation system. Focusing on improving the maintenance of content could result in something really useful.

Importing documentation from code repositories seems interesting, but not really actionable until we determine the destination of that import, which I think requires first defining goals.

**Comment by sreynen** [comment]
Last week the discussion was focused on importing documentation from Git repositories into a site (probably Drupal) where it could be read, but not edited, alongside documentation created directly on the site. This week the discussion was focused on the other systems we're already using for some documentation, which shifted the project focus to something that can unify documentation across various systems, possibly structured as an existing search tool (e.g. Solr or Elastic) with importers for specific sources (e.g. Git, Google Drive, Basecamp, JIRA).

Looking over the functional requirements outlined here, standardizing structure to the documentation and maintaining connections between documents seem like the biggest challenges with this approach. I expect those are solvable problems given more thought. The new consolidation-based approach seems like a big enough departure from the original pull request here that I'm going to close this one.

**Pull request closed without merging**
